# build environment
FROM node:13.12.0-alpine as build
WORKDIR /app
ARG BUILD_ID
RUN "echo $BUILD_ID"
LABEL stage=builder
LABEL build=$BUILD_ID
ENV PATH /app/node_modules/.bin:$PATH
#RUN npm install --silent
COPY package.json ./
COPY package-lock.json ./
RUN npm ci --silent
RUN npm install react-scripts@3.4.1 -g --silent
COPY . ./
RUN npm run build:dev

  # production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
